// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/younghan/project/mine/project-module-frontend/docs/react-feature/forwardRef.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/younghan/project/mine/project-module-frontend/docs/react-feature/forwardRef.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/Users/younghan/project/mine/project-module-frontend/docs/react-feature/effect.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/younghan/project/mine/project-module-frontend/docs/react-feature/effect.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/younghan/project/mine/project-module-frontend/docs/react-feature/index.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/younghan/project/mine/project-module-frontend/docs/react-feature/index.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/younghan/project/mine/project-module-frontend/docs/component/calendar.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/younghan/project/mine/project-module-frontend/docs/component/calendar.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from '/Users/younghan/project/mine/project-module-frontend/docs/component/message.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/younghan/project/mine/project-module-frontend/docs/component/message.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from '/Users/younghan/project/mine/project-module-frontend/docs/component/virtual.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/younghan/project/mine/project-module-frontend/docs/component/virtual.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from '/Users/younghan/project/mine/project-module-frontend/docs/animate/feature.md?type=frontmatter';
import { demoIndex as dmi6 } from '/Users/younghan/project/mine/project-module-frontend/docs/animate/feature.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from '/Users/younghan/project/mine/project-module-frontend/docs/animate/loading.md?type=frontmatter';
import { demoIndex as dmi7 } from '/Users/younghan/project/mine/project-module-frontend/docs/animate/loading.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from '/Users/younghan/project/mine/project-module-frontend/docs/animate/marquee.md?type=frontmatter';
import { demoIndex as dmi8 } from '/Users/younghan/project/mine/project-module-frontend/docs/animate/marquee.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from '/Users/younghan/project/mine/project-module-frontend/docs/component/index.md?type=frontmatter';
import { demoIndex as dmi9 } from '/Users/younghan/project/mine/project-module-frontend/docs/component/index.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from '/Users/younghan/project/mine/project-module-frontend/docs/animate/banner.md?type=frontmatter';
import { demoIndex as dmi10 } from '/Users/younghan/project/mine/project-module-frontend/docs/animate/banner.md?type=demo-index';
import { frontmatter as fm11, toc as t11 } from '/Users/younghan/project/mine/project-module-frontend/docs/animate/spring.md?type=frontmatter';
import { demoIndex as dmi11 } from '/Users/younghan/project/mine/project-module-frontend/docs/animate/spring.md?type=demo-index';
import { frontmatter as fm12, toc as t12 } from '/Users/younghan/project/mine/project-module-frontend/docs/component/icon.md?type=frontmatter';
import { demoIndex as dmi12 } from '/Users/younghan/project/mine/project-module-frontend/docs/component/icon.md?type=demo-index';
import { frontmatter as fm13, toc as t13 } from '/Users/younghan/project/mine/project-module-frontend/docs/animate/index.md?type=frontmatter';
import { demoIndex as dmi13 } from '/Users/younghan/project/mine/project-module-frontend/docs/animate/index.md?type=demo-index';
import { frontmatter as fm14, toc as t14 } from '/Users/younghan/project/mine/project-module-frontend/docs/css/instance.md?type=frontmatter';
import { demoIndex as dmi14 } from '/Users/younghan/project/mine/project-module-frontend/docs/css/instance.md?type=demo-index';
import { frontmatter as fm15, toc as t15 } from '/Users/younghan/project/mine/project-module-frontend/docs/css/index.md?type=frontmatter';
import { demoIndex as dmi15 } from '/Users/younghan/project/mine/project-module-frontend/docs/css/index.md?type=demo-index';
import { frontmatter as fm16, toc as t16 } from '/Users/younghan/project/mine/project-module-frontend/docs/index.md?type=frontmatter';
import { demoIndex as dmi16 } from '/Users/younghan/project/mine/project-module-frontend/docs/index.md?type=demo-index';

export const filesMeta = {
  'docs/react-feature/forwardRef': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/react-feature/forwardRef.md?type=text'),
  },
  'docs/react-feature/effect': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/react-feature/effect.md?type=text'),
  },
  'docs/react-feature/index': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/react-feature/index.md?type=text'),
  },
  'docs/component/calendar': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/component/calendar.md?type=text'),
  },
  'docs/component/message': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/component/message.md?type=text'),
  },
  'docs/component/virtual': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/component/virtual.md?type=text'),
  },
  'docs/animate/feature': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/animate/feature.md?type=text'),
  },
  'docs/animate/loading': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/animate/loading.md?type=text'),
  },
  'docs/animate/marquee': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/animate/marquee.md?type=text'),
  },
  'docs/component/index': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/component/index.md?type=text'),
  },
  'docs/animate/banner': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/animate/banner.md?type=text'),
  },
  'docs/animate/spring': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/animate/spring.md?type=text'),
  },
  'docs/component/icon': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/component/icon.md?type=text'),
  },
  'docs/animate/index': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/animate/index.md?type=text'),
  },
  'docs/css/instance': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/css/instance.md?type=text'),
  },
  'docs/css/index': {
    frontmatter: fm15,
    toc: t15,
    demoIndex: dmi15,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/css/index.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm16,
    toc: t16,
    demoIndex: dmi16,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/younghan/project/mine/project-module-frontend/docs/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
